name: TestCafeCI

on: [push]

jobs:
  build:
    name: Run Tests Operating Systems
    runs-on: $
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: 12
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: $
      - uses: actions/checkout@v1
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome tests"