name: TestCafeCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: testcafe/testcafe

    steps:
      - uses: actions/checkout@v1
      - name: npm install and build
        run: |
          npm install
          npm run test:ci
