name: TestCafeCI

on: [push]

jobs:
  build:
    name: Run Tests Operating Systems
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome:headless tests/"
